[package]
name = "mspc_ipc"
version = "0.1.2"
edition = "2021"
license = "Apache-2.0"
description = "Multi producer single consumer ring buffer for inter-process communication"

[dependencies]
anyhow = "1.0.86"
libc = "0.2.155"
memmap = "0.7.0"
